import requests

host = 'rating-serving-env.eba-drd5pjpn.us-west-1.elasticbeanstalk.com'
url = f'http://{host}/predict'

boardgame = {
    'max_players': 4,
 'max_playtime': 30,
 'min_age': 10,
 'min_players': 3,
 'min_playtime': 30,
 'playing_time': 30,
 'year_published': 1997,
 'users_rated': 269,
 'Abstract Strategy': 0,
 'Action / Dexterity': 0,
 'Adventure': 0,
 'Age of Reason': 0,
 'American Civil War': 0,
 'American Indian Wars': 0,
 'American Revolutionary War': 0,
 'American West': 0,
 'Ancient': 0,
 'Animals': 0,
 'Arabian': 0,
 'Aviation / Flight': 0,
 'Bluffing': 0,
 'Book': 0,
 'Card Game': 1,
 "Children's Game": 0,
 'City Building': 0,
 'Civil War': 0,
 'Civilization': 0,
 'Collectible Components': 0,
 'Comic Book / Strip': 0,
 'Deduction': 0,
 'Dice': 0,
 'Economic': 0,
 'Educational': 0,
 'Electronic': 0,
 'Environmental': 0,
 'Expansion for Base-game': 0,
 'Exploration': 0,
 'Fantasy': 0,
 'Farming': 0,
 'Fighting': 0,
 'Game System': 0,
 'Horror': 0,
 'Humor': 0,
 'Industry / Manufacturing': 0,
 'Korean War': 0,
 'Mafia': 0,
 'Math': 0,
 'Mature / Adult': 0,
 'Maze': 0,
 'Medical': 0,
 'Medieval': 0,
 'Memory': 0,
 'Miniatures': 0,
 'Modern Warfare': 0,
 'Movies / TV / Radio theme': 0,
 'Murder/Mystery': 0,
 'Music': 0,
 'Mythology': 0,
 'Napoleonic': 0,
 'Nautical': 0,
 'Negotiation': 0,
 'Novel-based': 0,
 'Number': 0,
 'Party Game': 0,
 'Pike and Shot': 0,
 'Pirates': 0,
 'Political': 0,
 'Post-Napoleonic': 0,
 'Prehistoric': 0,
 'Print & Play': 0,
 'Puzzle': 0,
 'Racing': 0,
 'Real-time': 0,
 'Religious': 0,
 'Renaissance': 0,
 'Science Fiction': 0,
 'Space Exploration': 0,
 'Spies/Secret Agents': 0,
 'Sports': 0,
 'Territory Building': 0,
 'Trains': 0,
 'Transportation': 0,
 'Travel': 0,
 'Trivia': 0,
 'Video Game Theme': 0,
 'Vietnam War': 0,
 'Wargame': 0,
 'Word Game': 0,
 'World War I': 0,
 'World War II': 0,
 'Zombies': 0,
 'Acting': 0,
 'Action / Movement Programming': 0,
 'Action Point Allowance System': 0,
 'Area Control / Area Influence': 0,
 'Area Enclosure': 0,
 'Area Movement': 0,
 'Area-Impulse': 0,
 'Auction/Bidding': 0,
 'Betting/Wagering': 0,
 'Campaign / Battle Card Driven': 0,
 'Card Drafting': 0,
 'Chit-Pull System': 0,
 'Co-operative Play': 0,
 'Commodity Speculation': 0,
 'Crayon Rail System': 0,
 'Deck / Pool Building': 0,
 'Dice Rolling': 0,
 'Grid Movement': 0,
 'Hand Management': 0,
 'Hex-and-Counter': 0,
 'Line Drawing': 0,
 'Modular Board': 0,
 'Paper-and-Pencil': 0,
 'Partnerships': 0,
 'Pattern Building': 0,
 'Pattern Recognition': 0,
 'Pick-up and Deliver': 0,
 'Player Elimination': 0,
 'Point to Point Movement': 0,
 'Press Your Luck': 0,
 'Rock-Paper-Scissors': 0,
 'Role Playing': 0,
 'Roll / Spin and Move': 0,
 'Route/Network Building': 0,
 'Secret Unit Deployment': 0,
 'Set Collection': 1,
 'Simulation': 0,
 'Simultaneous Action Selection': 0,
 'Singing': 0,
 'Stock Holding': 0,
 'Storytelling': 0,
 'Take That': 0,
 'Tile Placement': 0,
 'Time Track': 0,
 'Trading': 0,
 'Trick-taking': 0,
 'Variable Phase Order': 0,
 'Variable Player Powers': 0,
 'Voting': 0,
 'Worker Placement': 0
}

response = requests.post(url, json=boardgame).json()
print(response)